"""

Revision ID: 0d37e4c37331
Revises: 2464992bd3e5
Create Date: 2026-06-15 16:22:07.827676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d37e4c37331'
down_revision: Union[str, Sequence[str], None] = '2464992bd3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
